-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 21, 2025 at 07:51 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `viter_fbs_v2`
--

-- --------------------------------------------------------

--
-- Table structure for table `fbsv2_industry_testimonial`
--

CREATE TABLE `fbsv2_industry_testimonial` (
  `industry_testimonial_aid` int(11) NOT NULL,
  `industry_testimonial_img` text NOT NULL,
  `industry_testimonial_logo` text NOT NULL,
  `industry_testimonial_name` varchar(150) NOT NULL,
  `industry_testimonial_position` varchar(150) NOT NULL,
  `industry_testimonial_message` text NOT NULL,
  `industry_testimonial_category` varchar(100) NOT NULL,
  `industry_testimonial_company` varchar(150) NOT NULL,
  `industry_testimonial_created` datetime NOT NULL,
  `industry_testimonial_datetime` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `fbsv2_industry_testimonial`
--

INSERT INTO `fbsv2_industry_testimonial` (`industry_testimonial_aid`, `industry_testimonial_img`, `industry_testimonial_logo`, `industry_testimonial_name`, `industry_testimonial_position`, `industry_testimonial_message`, `industry_testimonial_category`, `industry_testimonial_company`, `industry_testimonial_created`, `industry_testimonial_datetime`) VALUES
(1, '[{\"name\":\"dennis-siano2.png\",\"id\":\"12LQEjy3RW4WfHtZcq-SYVCVspeTaNmH-\",\"datetime\":\"2025-03-21 13:50:28\"}]', '[{\"name\":\"dtod-bpo (2).png\",\"id\":\"1bWMYIiz2OgKgQC6frwOXp9XKSWBDSrbt\",\"datetime\":\"2025-03-21 13:50:34\"}]', 'Dennis Ray Siano', 'Chief Excutive Officer Owner', 'Excellent HRIS Provider with Outstanding Support!\nI started working with Frontline Business Solutions Inc. earlier this year, and so far, I’m extremely satisfied with their HRIS solutions. Their platform has streamlined our HR processes, making tasks like employee management, payroll, and reporting much more efficient. What truly stands out is the level of support we’ve received from their team.\nOur account manager has been incredibly helpful and responsive throughout the entire process, ensuring that we’re getting the most out of the system. Anytime we have questions or need assistance, they are always there to provide guidance and solutions quickly.\nOverall, I highly recommend Frontline Business Solutions Inc. for anyone looking for a reliable and supportive HRIS provider. Their service has been excellent, and their team truly understands the needs of their clients.', 'HR Information System', '', '0000-00-00 00:00:00', '2025-03-21 13:50:25'),
(2, '[{\"name\":\"kimbell-reyes.png\",\"id\":\"1N3MYwiu4rtDmYd_AMoaSlO6cqM2JNeQL\",\"datetime\":\"2025-03-21 13:49:59\"}]', '[{\"name\":\"aka-global (1).png\",\"id\":\"1zz8iI9oXA0g6ygbgwiQ3UIsdfurrgcOX\",\"datetime\":\"2025-03-21 13:50:05\"}]', 'Kimbell John Reyes', 'Chief Executive Officer', 'Frontline Business Solutions is indeed a partner to innovative success of a company. A connection of employer and employee. ', 'HR Information System', '', '2024-11-04 12:32:13', '2025-03-21 13:49:56'),
(3, '[{\"name\":\"alexander-ubeda.png\",\"id\":\"1ChP6jT9ccSIdOMA5WiAH8bIc-ixt2ngD\",\"datetime\":\"2025-03-21 13:58:57\"}]', '[{\"name\":\"fca-logo-horizontal.png\",\"id\":\"179fIlPMvm1CQsnAbPbDoborjrAPOuiWF\",\"datetime\":\"2025-03-21 13:59:01\"}]', 'Alexander Ubeda', 'IT Department Head', 'Frontline Business Solutions not only tailored the online enrollment system to Frontline Christian Academy\'s specific needs but also provided exceptional support, ensuring they were always available for any adjustments we required.', 'School Enrollment System', '', '0000-00-00 00:00:00', '2025-03-21 13:59:06'),
(4, '[{\"name\":\"judea-delos-santos.png\",\"id\":\"1qrp0GoCcDmCicNBIkVz3N6i0HXkZHyIR\",\"datetime\":\"2025-03-21 14:00:50\"}]', '[{\"name\":\"ftc-logo.png\",\"id\":\"11srn6kZcStwVI67r6VIY3ocJpTvl7uhD\",\"datetime\":\"2025-03-21 14:00:52\"}]', 'Judea Delos Santos', 'Asst. Managing Director / Comm. & Dev. Staff', 'FBS has been an incredible partner in helping us enhance the functionality and efficiency of our FTC website. They seamlessly upgraded our backend systems, greatly improving our ability to manage donations and streamlining other critical IT requests. Their team’s professionalism, attention to detail, and commitment to supporting our mission of serving abandoned, abused, and neglected children have been invaluable. Thanks to their expertise, we are now able to operate more smoothly and efficiently, allowing us to focus on making a bigger difference for the kids we serve. We highly recommend Frontline Business Solution for any organization in need of reliable and innovative IT solutions.', 'Online Donation System', '', '2024-11-04 12:35:33', '2025-03-21 14:00:57'),
(5, '[{\"name\":\"bethany-acoba.png\",\"id\":\"1GEB9YEBlTiBDs-dXkuhYAowSL_Mqdihy\",\"datetime\":\"2025-03-21 14:01:25\"}]', '[{\"name\":\"logo-pfm.png\",\"id\":\"1RPFWL8sgyTtMevEHUn1wnwbAYNnaQZP9\",\"datetime\":\"2025-03-21 14:01:27\"}]', 'Bethany P. Acoba', 'Donor Communications and Care Coordinator', 'The online donation platform that FBS developed has enhanced our website. The process is straightforward and user-friendly, making it easy for our partners and friends from around the world to support our mission. I couldn\'t be happier with the results! ', 'Online Donation System', '', '2024-11-04 12:37:24', '2025-03-21 14:01:32'),
(6, '[{\"name\":\"lara-yedra.png\",\"id\":\"1GABXXfaoQY0z7Q-l-5t6duWoH2hN15_D\",\"datetime\":\"2025-03-21 14:08:58\"}]', '[{\"name\":\"stms.png\",\"id\":\"1p34s1SnZCFTjAPO_ZM6O1SGCie7dSfjg\",\"datetime\":\"2025-03-21 14:09:02\"}]', 'Lara Jane P. Yedra', 'Work Immersion Teacher', 'We extend our deepest gratitude to Frontline Business Solutions for being an outstanding partner in our Work Immersion program. Your organization provided our students with valuable, real-world experiences that greatly enhanced their skills and understanding of their chosen fields. The support and mentorship offered by your team created an ideal learning environment, fostering both professional and personal growth.                                                                                                                                                Your commitment to nurturing young talent and your willingness to involve them in meaningful projects have had a profound impact on their future careers. We truly appreciate the collaboration and look forward to more successful partnerships in the years to come.', 'High School Work Immersion', 'St. Therese Montessori School', '2024-11-04 13:13:22', '2025-03-21 14:09:09'),
(7, '[{\"name\":\"olivia-almarez.png\",\"id\":\"1KQwTA0mDcGn8pEMlMWqjnn3YV-sN7FmH\",\"datetime\":\"2025-03-21 14:03:39\"}]', '[{\"name\":\"sti.png\",\"id\":\"1qelwJ9hwqi4n-MNLK1xMZoL1c6We_1kS\",\"datetime\":\"2025-03-21 14:03:42\"}]', 'Ms. Olivia Almarez', 'OJT Coordinator', 'Frontline Business Solution has been one of STI San Pablo\'s most trusted partners for several years. We at STI are truly grateful for the exceptional knowledge and experience FBS has provided to our On-the-Job trainee students in IT and Engineering, as well as for the kindness and support shown coming from the people of FBS.', 'College On-the-job- Training', 'STI San Pablo Campus', '2024-11-04 13:15:14', '2025-03-21 14:03:46'),
(8, '[{\"name\":\"angelou-almare-medina.png\",\"id\":\"12-5krbvcLIylY0f0m-jk2xNuSXQUtsZr\",\"datetime\":\"2025-03-21 14:04:22\"}]', '[{\"name\":\"sti.png\",\"id\":\"1xl-CEhvs5YuMkJ3ZSJXHFWXg9dydn3sj\",\"datetime\":\"2025-03-21 14:04:25\"}]', 'Mrs. Angelou Almare-Medina', '', 'FBS\' internship program provided great opportunity for students to experience actual industry-related tasks which greatly honed their skills. This also enhanced their professional capabilities and served as a valuable foundation for their future career.', 'College On-the-job- Training', 'STI San Pablo Campus', '2024-11-04 13:16:32', '2025-03-21 14:04:35'),
(9, '[{\"name\":\"ariel-ferrer.png\",\"id\":\"10Vh1pLl-MzSCtdxVe6mSXDOdq9wH0l51\",\"datetime\":\"2025-03-21 14:13:16\"}]', '[{\"name\":\"lspu.png\",\"id\":\"1CMvg8n8vv_X4S6ZsbgxDS9IDKPk33mr_\",\"datetime\":\"2025-03-21 14:13:18\"}]', 'Ms. Ariel Angeni Ferrer', 'BS Computer Engineering Graduate', 'My experience at Frontline Business Solution has truly been a great journey. I gained a wealth of knowledge in front-end web design, equipping me with essential skills in HTML, CSS, and JavaScript. Most importantly, the people there are truly amazing and passionate about their work. To sum it up, my experience at FBS was fun!', 'Continuing Studies', '', '2024-11-04 13:17:24', '2025-03-21 14:13:23'),
(10, '[{\"name\":\"emilio-macaso.png\",\"id\":\"1cBHIXHsOSB9Bn1Dt9Ntms0uYYX72YyEK\",\"datetime\":\"2025-03-21 14:05:23\"}]', '[{\"name\":\"dlsl_official_logo.png\",\"id\":\"1UiAnCtnf0HeS0A79-WFj1oytGHxaw-Nz\",\"datetime\":\"2025-03-21 14:05:26\"}]', 'Emilio Manuel Macaso', 'IT Faculty, La Salle Lipax', 'A successful internship may be defined as one that provides the following: meaningful and relevant work, formal and informal training, social opportunities to build personal skills and relationships, and continuous connections even after the internship has ended.  The Information Technology program of De La Salle Lipa is fortunate to have found all these with the internship program of Frontline Business Solutions.  Our student interns had fulfilling internships with FBS, with their holistic approach in honing both their technical. leadership, and personal skills, and making them more ready to face the exciting world of IT.\nWe look forward to partnering with FBS to develop and nurture future-ready IT professionals.', 'College On-the-job- Training', '', '2024-11-04 13:18:31', '2025-03-21 14:05:20'),
(11, '[{\"name\":\"kevinroy-nativo.png\",\"id\":\"1Y2WtdfIXIslAdH09G24V-Rsu-Jw1ZST-\",\"datetime\":\"2025-03-21 14:14:09\"}]', '[{\"name\":\"aclc.png\",\"id\":\"1vYnIlTfCRqADuOqmd2VoIZkyfQYR_22h\",\"datetime\":\"2025-03-21 14:14:12\"}]', 'Mr. Kevin Roy N. Oreña', 'Freelancer', 'After graduating 5 years ago, I didn\'t have the chance to apply my programming skills in my career. So, I decided to further my studies at FBS. Through FBS, I was able to refresh my existing knowledge and acquire new skills in web development, including HTML/CSS, SASS, Tailwind, Figma, WordPress, and JavaScript, which I have already been using in my freelancing career.', 'Continuing Studies', '', '2024-11-04 13:20:11', '2025-03-21 14:14:19'),
(12, '[{\"name\":\"chelsea-lim.png\",\"id\":\"1shYDdr4hMblsQDyPKqb9djAVzNd22xT8\",\"datetime\":\"2025-03-21 14:09:39\"}]', '[{\"name\":\"spc.png\",\"id\":\"1l0XWpV97UJOgBzbfRJVkuuRVymjnRg3v\",\"datetime\":\"2025-03-21 14:09:42\"}]', 'Ms. Chelsea Lim', '', 'Frontline Business Solutions helped my students grow in every aspect. They were trained as part of the company and were really excited to tell me their stories. I saw how the company changed my students in facing problems, way of learning, discipline and understanding. I would recommend Frontline Business Solutions if you want exceptional training and experience.', 'High School Work Immersion', 'San Pablo Colleges', '2024-11-04 13:21:05', '2025-03-21 14:09:50'),
(13, '[{\"name\":\"jake-gamaro.webp\",\"id\":\"1Qbaaau3xEa4bf8jNwnJc_BhY6Xj2vojk\",\"datetime\":\"2025-03-21 14:15:01\"}]', '[{\"name\":\"lspu.png\",\"id\":\"1KJMsn7DB8Q2Uo8fr85epb5ELLprmg7Fq\",\"datetime\":\"2025-03-21 14:15:04\"}]', 'Jake Ansel Gamaro', 'Freelancer', 'The immersion program was incredibly beneficial for me. I loved diving into front-end web development, learning tools like Figma for prototyping and web designing, and exploring CSS with SASS and Tailwind. Getting hands-on experience with WordPress really boosted my confidence. I’m thankful for the supportive instructors and the skills I gained for my career!', 'Continuing Studies', '', '0000-00-00 00:00:00', '2025-03-21 14:15:11'),
(14, '[{\"name\":\"joesua-manzanero.png\",\"id\":\"1C-cZSKdeqGuyHzWnKLBL_md3fRMxCWIf\",\"datetime\":\"2025-03-21 14:06:13\"}]', '[{\"name\":\"lspu.png\",\"id\":\"1iRv8ACjH7lp5KqAaN31cJ38CV6r6YcVB\",\"datetime\":\"2025-03-21 14:06:16\"}]', 'Joesua R. Manzanero', 'Faculty, Program Coordinator, BS in Information Technology  OJT Coordinator, College of Computer Studies', 'Frontline Business Solutions has demonstrated a commendable commitment to fostering the professional growth of our students through their intensive Internship programs. The hands-on experience provided during the training is invaluable, allowing students to apply theoretical knowledge in real-world settings. This practical exposure significantly enhances their readiness for the workforce.\nMoreover, Frontline offers high-end facilities equipped with the latest technology, ensuring that interns are well-prepared to meet industry standards. The emphasis on developing industry-standard competencies further underscores their dedication to producing skilled professionals who can thrive in today’s competitive landscape.\nWe appreciate Frontline Business Solutions for their partnership and commitment to the development of our students. Such opportunities are crucial in shaping the next generation of innovators in the IT and CS sector.\nThank you for your continued support.', 'College On-the-job- Training', 'Laguna State Polytechnic University- San Pablo City Campus', '0000-00-00 00:00:00', '2025-03-21 14:06:22'),
(17, '[{\"name\":\"kimbell-reyes.png\",\"id\":\"1daHDbyjJOkxBvEs--V4k7AsgnfyD2G8C\",\"datetime\":\"2025-03-21 13:55:58\"}]', '[{\"name\":\"aka-global (1).png\",\"id\":\"1iP5iM3k2ZrKzMlbvBE04fGRJseNNxoQj\",\"datetime\":\"2025-03-21 13:56:02\"}]', 'Kimbell John Reyes', 'Chief Executive Officer', 'Frontline Business Solutions is indeed a partner to innovative success of a company. A connection of employer and employee.', 'Online Payroll System', '', '0000-00-00 00:00:00', '2025-03-21 13:56:11'),
(18, '[{\"name\":\"dennis-siano2.png\",\"id\":\"1oDXyJYuFjEsM29UCbEElrj7F-pI0gdhv\",\"datetime\":\"2025-03-21 13:55:37\"}]', '[{\"name\":\"dtod-bpo (2).png\",\"id\":\"1ckBM_JbnfRQQJetr_6jjOx8xlim92LA3\",\"datetime\":\"2025-03-21 13:55:41\"}]', 'Dennis Ray Siano', 'Chief Executive Officer Owner', 'Excellent HRIS Provider with Outstanding Support! Their platform has streamlined our HR processes, making tasks like employee management, payroll, and reporting much more efficient. What truly stands out is the level of support we’ve received from their team. I highly recommend Frontline Business Solutions Inc. for anyone looking for a reliable and supportive HRIS provider. Their service has been excellent, and their team truly understands the needs of their clients. ', 'Online Payroll System', 'D to D BPO Solutions', '0000-00-00 00:00:00', '2025-03-21 13:56:07'),
(19, '[{\"name\":\"jim-davison.png\",\"id\":\"19KsbePRSf9ZJ-dLfEIazZrEz3_SgkLlZ\",\"datetime\":\"2025-03-21 14:23:50\"}]', '[{\"name\":\"logo-avant (1).png\",\"id\":\"1kJiQDWfax--7BgUfD_neRe_R7N7Jgm-F\",\"datetime\":\"2025-03-21 14:23:53\"}]', 'James Davidson', 'Managing Director & President', 'Frontline Business Solutions is beyond an exceptional firm. Professional courtesy, responsiveness, competence, and client service are only a few of the many high level qualities that Frontline’s team exhibit. Frontline exemplifies the golden rule by treating its clients as it would like to be treated. Every Frontline team member with whom Avant Advisory Group has dealt has been a true blessing. Finally, based on Avant Advisory Group’s several years of working with Frontline personnel, I can say that they work heartily for their clients as if they are working for the Lord. (Colossians 3:23-24) Thank you for what you do, Frontline!', 'Administrative', 'Avant Advisory Group', '0000-00-00 00:00:00', '2025-03-21 14:24:11'),
(20, '[{\"name\":\"josh-howard.png\",\"id\":\"1iwJdOiO5zhq9UIewo3D9lcXRez3j2CVJ\",\"datetime\":\"2025-03-21 14:25:27\"}]', '[{\"name\":\"logo-ignite.png\",\"id\":\"1-gVT9j35BaTC7nSjyrOkXf1pF6yYmR2Q\",\"datetime\":\"2025-03-21 14:25:31\"}]', 'Josh Howard', 'Chief Executive Officer', 'Our partnership with Frontline has been the best financial investment we’ve ever made. The team is absolutely amazing and always goes above and beyond in every area. I highly recommend them!!', 'Administrative', 'Ignite Investment Group', '0000-00-00 00:00:00', '2025-03-21 14:25:36'),
(21, '[{\"name\":\"teresa-heyne.png\",\"id\":\"1x2gZuyRbBYVmyFDtOaOLVAxzBsDn89pg\",\"datetime\":\"2025-03-21 14:26:45\"}]', '[{\"name\":\"jcceos-logo.png\",\"id\":\"1-r27J6A_ogkJXJyktaQA7CTL5V6rv5g4\",\"datetime\":\"2025-03-21 14:26:48\"}]', 'Teresa Heyne', 'Overseer, Director of Operations', 'I am extremely impressed with Frontline Business Solution\'s dedication to excellence. Their team demonstrates outstanding professionalism and attention to detail with their Personal Assistant and Graphic Design Services.   When we transitioned our CRM over to HubSpot, they went above and beyond to learn and implement all of the marketing automation processes and reporting analytics.  The results have positively impacted our ministry, and we look forward to continuing our relationship with them.', 'Administrative', '', '2024-11-05 09:44:07', '2025-03-21 14:27:03'),
(22, '[{\"name\":\"josh-howard.png\",\"id\":\"1YNV0_jN9M8Q_cfS95VREvn3a-WX4lNYD\",\"datetime\":\"2025-03-21 14:32:12\"}]', '[{\"name\":\"logo-ignite.png\",\"id\":\"150nyhpH01Ozm19f10-t4xwRCenrY-dmm\",\"datetime\":\"2025-03-21 14:32:15\"}]', 'Josh Howard', 'Chief Executive Officer', 'Our partnership with Frontline has been the best financial investment we’ve ever made. The team is absolutely amazing and always goes above and beyond in every area. I highly recommend them!!', 'Business Support', 'Ignite Investment Group', '0000-00-00 00:00:00', '2025-03-21 14:32:27'),
(23, '[{\"name\":\"jim-davison.png\",\"id\":\"1lbCbq4GNx0aVDpEyCDWnV2OS_CfAdEc7\",\"datetime\":\"2025-03-21 14:32:57\"}]', '[{\"name\":\"logo-avant (1).png\",\"id\":\"1OmXYixSRyZN9Hg3MbWhTiXbetAl0N-Ii\",\"datetime\":\"2025-03-21 14:33:01\"}]', 'James Davidson', 'Managing Director & President', 'Frontline Business Solutions is beyond an exceptional firm. Professional courtesy, responsiveness, competence, and client service are only a few of the many high level qualities that Frontline’s team exhibit. Frontline exemplifies the golden rule by treating its clients as it would like to be treated. Every Frontline team member with whom Avant Advisory Group has dealt has been a true blessing. Finally, based on Avant Advisory Group’s several years of working with Frontline personnel, and especially Mike DeJesus, I can say that they work heartily for their clients as if they are working for the Lord. (Colossians 3:23-24) Thank you for what you do, Frontline!', 'Business Support', '', '2024-11-05 09:49:58', '2025-03-21 14:33:06'),
(24, '[{\"name\":\"teresa-heyne.png\",\"id\":\"1AmDUlLSiAN0FGXB3Q0Yx66dwT2HFBL_C\",\"datetime\":\"2025-03-21 14:34:15\"}]', '[{\"name\":\"jcceos-logo.png\",\"id\":\"1nWkZ1D6AOnCqy6ovnI7Y6yNJNtxS8FhM\",\"datetime\":\"2025-03-21 14:34:18\"}]', 'Teresa Heyne', 'Overseer, Director of Operations', 'I am extremely impressed with Frontline Business Solution\'s dedication to excellence. Their team demonstrates outstanding professionalism and attention to detail with their Personal Assistant and Graphic Design Services.   When we transitioned our CRM over to HubSpot, they went above and beyond to learn and implement all of the marketing automation processes and reporting analytics.  The results have positively impacted our ministry, and we look forward to continuing our relationship with them.', 'Marketing', '', '2024-11-05 09:55:23', '2025-03-21 14:34:23'),
(25, '[{\"name\":\"jim-davison.png\",\"id\":\"1wd5WOShHrqjdgi4MB_DZKs1WpprXmnxN\",\"datetime\":\"2025-03-21 14:35:22\"}]', '[{\"name\":\"logo-avant (1).png\",\"id\":\"15n1SA9fMGE6S-jyQpXZEKl574zUV5Aaz\",\"datetime\":\"2025-03-21 14:35:25\"}]', 'James Davidson', 'Managing Director & President', 'Frontline Business Solutions is beyond an exceptional firm. Professional courtesy, responsiveness, competence, and client service are only a few of the many high level qualities that Frontline’s team exhibit. Frontline exemplifies the golden rule by treating its clients as it would like to be treated. Every Frontline team member with whom Avant Advisory Group has dealt has been a true blessing. Finally, based on Avant Advisory Group’s several years of working with Frontline personnel, and especially Mike DeJesus, I can say that they work heartily for their clients as if they are working for the Lord. (Colossians 3:23-24) Thank you for what you do, Frontline!', 'Marketing', '', '2024-11-05 09:56:28', '2025-03-21 14:35:28'),
(26, '[{\"name\":\"josh-howard (1).png\",\"id\":\"1zQobIz2R77BEB9N-wgzNhR7_BQPOelMQ\",\"datetime\":\"2025-03-21 14:35:48\"}]', '[{\"name\":\"logo-ignite (1).png\",\"id\":\"1ptBotKONmoiAyBouW849TUTbnzUs_1XN\",\"datetime\":\"2025-03-21 14:35:51\"}]', 'Josh Howard', 'Chief Executive Officer', 'Our partnership with Frontline has been the best financial investment we’ve ever made. The team is absolutely amazing and always goes above and beyond in every area. I highly recommend them!!', 'Marketing', '', '2024-11-05 09:57:17', '2025-03-21 14:35:58'),
(27, '[{\"name\":\"james-sunderland.png\",\"id\":\"1v4Q0RbD20lONtppG3pRtCOSuXHS1K10f\",\"datetime\":\"2025-03-21 14:40:42\"}]', '[{\"name\":\"logo-ottm.png\",\"id\":\"11GRo250UolXTnPj3E2sMEEZL1cjqNbe6\",\"datetime\":\"2025-03-21 14:40:45\"}]', 'James Sunderland', 'VP Creative', 'The team at Frontline is incredible. They genuinely care about our needs and share in our vision of success. We are proud to call them a business partner and appreciate all the hard work they do for us.', 'Web Design', '', '2024-11-05 12:05:37', '2025-03-21 14:40:49'),
(28, '[{\"name\":\"duane-masters.png\",\"id\":\"1Mehs8d2hKABDp3OWqjz79UEL25fKlF-y\",\"datetime\":\"2025-03-21 14:41:29\"}]', '[{\"name\":\"logo-world-focus (1).png\",\"id\":\"1kP5Pm5uqhfnJ3iGByfeLcZjQTC5LBT-K\",\"datetime\":\"2025-03-21 14:41:32\"}]', 'Pastor Duane Mastersx', 'Executive Director', 'Frontline has been an incredible organization to work with. They are friendly, accommodating, and professional, but what stands out to me the most is how responsive they are. Whenever I have a problem or request, not only have I always received a response within the day, but their team has also met my needs the same day. I’m not sure I have ever worked with an organization as responsive as they are. I would highly recommend working with them.', 'Web Design', '', '0000-00-00 00:00:00', '2025-03-21 14:41:26'),
(29, '[{\"name\":\"james-sunderland.png\",\"id\":\"1nuTnwvQwmtsyVv5avOFrkNFo4UavxAFG\",\"datetime\":\"2025-03-21 14:39:46\"}]', '[{\"name\":\"logo-ottm.png\",\"id\":\"1lhBtEu5PP03qk1tu2pWSMl2fP5yjPHcQ\",\"datetime\":\"2025-03-21 14:39:48\"}]', 'James Sunderland', 'VP Creative', 'The team at Frontline is incredible. They genuinely care about our needs and share in our vision of success. We are proud to call them a business partner and appreciate all the hard work they do for us.', 'WordPress CMS Website', '', '0000-00-00 00:00:00', '2025-03-21 14:39:52'),
(30, '[{\"name\":\"jeffrey-seitz.png\",\"id\":\"1ewvWl_cQCGilyiFFgUC5NRQh7ZyINKuN\",\"datetime\":\"2025-03-21 14:39:01\"}]', '[{\"name\":\"logo-phixgenomics.png\",\"id\":\"10fxu-rFeqPJUN1pl7Rqsz1d6aOLWTxRi\",\"datetime\":\"2025-03-21 14:39:03\"}]', 'Jeffrey Seitz', 'Chief Executive Officer', 'I have worked with a number of different website developers, but none have been as responsive or as quick to turn the work around.', 'WordPress CMS Website', '', '2024-11-05 12:08:54', '2025-03-21 14:39:09'),
(31, '[{\"name\":\"rhodalynn-dayo.png\",\"id\":\"1Os_y8M-KZhMTXpoR_6efpgSV1ohEke1j\",\"datetime\":\"2025-03-21 14:37:56\"}]', '[{\"name\":\"logo-fca.png\",\"id\":\"18KoTybcrc557qZQyPf_CJOKKOdVO9AOv\",\"datetime\":\"2025-03-21 14:37:59\"}]', 'Rhoda Lynn Pessina-Dayo', 'School Directress', 'We enjoyed working together and meeting with the Frontline Business Solutions Staff when they built the website of Frontline Christian Academy.', 'WordPress CMS Website', '', '2024-11-05 12:10:14', '2025-03-21 14:38:21'),
(32, '[{\"name\":\"zymon-ramos.webp\",\"id\":\"1FLosStPmCCxPmpZ71DXgX0ZrCAj5a-xU\",\"datetime\":\"2025-03-21 14:15:48\"}]', '[{\"name\":\"lc.png\",\"id\":\"1kuzWltgEnRpscUtD4hqow8rQWi9-24RX\",\"datetime\":\"2025-03-21 14:15:51\"}]', 'Jinuel Zymon Ramos', 'BSCS Magna Cum Laude Batch 2023', 'As a lifelong learner, the continuing study program at Frontline Business Solutions was truly beneficial for my own personal and professional growth. The Front-End development training was exceptional, covering HTML, CSS, and other frameworks, while also focusing on coding efficiency and dynamic web design. Grateful for the excellent trainers and well-structured training program—truly worth it.', 'Continuing Studies', '', '0000-00-00 00:00:00', '2025-03-21 14:15:56'),
(33, '[{\"name\":\"andrey-ilagan.webp\",\"id\":\"1QsWfmLBlewl0XdRsTxF4ZMjqtvYmoOdX\",\"datetime\":\"2025-03-21 14:16:35\"}]', '[{\"name\":\"plsp.png\",\"id\":\"1_PWO3x7mES3MC35cWxMaCtfvtGSZCSzs\",\"datetime\":\"2025-03-21 14:16:38\"}]', 'Andrey Ilagan', 'BSCpE Batch 2024 Pamantasan ng Lungsod ng San Pablo', 'I\'ve gained a wealth of knowledge in web development through my experience at Frontline Business Solutions, especially their Continuing Study Program. The program’s hands-on approach and structured tutorials deepened my understanding of both front-end and back-end development. This practical learning environment encouraged continuous improvement and allowed me to confidently apply my skills to real-world projects, significantly enhancing my technical abilities. Thanks to this program, I am more confident and better equipped to handle complex web development challenges.', 'Continuing Studies', '', '0000-00-00 00:00:00', '2025-03-21 14:16:43'),
(34, '[{\"name\":\"kurt-balanial.webp\",\"id\":\"1MmjIUg23gwzsQml68eEDQqcO-Uhd1oeo\",\"datetime\":\"2025-03-21 14:12:36\"}]', '[{\"name\":\"plsp.png\",\"id\":\"1LDHR0ai_nAtZSqvfjB6__17g7_nMikpP\",\"datetime\":\"2025-03-21 14:12:42\"}]', 'Kurt Lui Balanial', 'BSCpE Batch 2024 Pamantasan ng Lungsod ng San Pablo', 'My training at Frontline Business Solutions was an invaluable experience that equipped me with essential skills in HTML, CSS, and Java. The supportive and professional environment made me feel empowered and ready to take on future challenges in the industry. This experience has truly prepared me for my career endeavors, leaving me more confident in my abilities.', 'Continuing Studies', '', '0000-00-00 00:00:00', '2025-03-21 14:13:01');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `fbsv2_industry_testimonial`
--
ALTER TABLE `fbsv2_industry_testimonial`
  ADD PRIMARY KEY (`industry_testimonial_aid`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `fbsv2_industry_testimonial`
--
ALTER TABLE `fbsv2_industry_testimonial`
  MODIFY `industry_testimonial_aid` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=36;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
